CREATE TABLE "user" (
    "id" UUID PRIMARY KEY,
    "login" VARCHAR(255) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "firstname" VARCHAR(255) NOT NULL,
    "surname" VARCHAR(255) NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('ACTIVE', 'LOCKED', 'ARCHIVED')),
    "version" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user_role" (
    "user_id" UUID,
    "role_id" SMALLINT NOT NULL,
    PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "role" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" VARCHAR(15) NOT NULL,
    "description" TEXT
);

CREATE TABLE "login_attempt" (
    "user_id" UUID PRIMARY KEY,
    "count" INTEGER NOT NULL DEFAULT 0,
    "last_attempt" TIMESTAMPTZ
);

CREATE TABLE "audit_trail" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "author_id" UUID,
    "event" VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMPTZ NOT NULL,
    "previous_data" JSONB NOT NULL,
    "changed_data" JSONB NOT NULL
);

CREATE TABLE "supplier" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "address" TEXT NOT NULL
);

CREATE TABLE "component" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" VARCHAR(15) NOT NULL CHECK (type IN ('RAW_MATERIAL', 'COMPONENT')),
    "reference" VARCHAR(255) UNIQUE NOT NULL,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('DRAFT', 'DISABLED', 'ACTIVE')),
    "supplier_id" BIGINT NOT NULL
);

CREATE TABLE "control_range_specifications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "component_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "method" VARCHAR(255) NOT NULL,
    "unit" VARCHAR(255) NOT NULL,
    "min" DOUBLE PRECISION NOT NULL,
    "max" DOUBLE PRECISION NOT NULL
);

CREATE TABLE "order" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('PENDING', 'RECEIVED', 'CANCELED'))
);

CREATE TABLE "order_line" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "component_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL
);

CREATE TABLE "batch" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "component_id" BIGINT NOT NULL,
    "label" VARCHAR(255),
    "internal_reference_number" VARCHAR(255) UNIQUE NOT NULL,
    "supplier_reference_number" VARCHAR(255) UNIQUE NOT NULL,
    "expiry_date" DATE NOT NULL,
    "reception_date" DATE NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('QUARANTINE', 'PENDING', 'RECEIVED', 'USED', 'REFUSED', 'EXPIRED', 'DESTROYED'))
);

CREATE TABLE "deviation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "batch_id" BIGINT NOT NULL,
    "code" VARCHAR(255) NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('OPENED', 'CLOSED')),
    "comment" TEXT
);

CREATE TABLE "analysis_results" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "batch_id" BIGINT NOT NULL,
    "specification_id" BIGINT NOT NULL,
    "value" DOUBLE PRECISION NOT NULL
);

COMMENT ON COLUMN "user"."version" IS 'Optimistic Locking';
COMMENT ON COLUMN "role"."label" IS 'ADMIN, SUPPLY, CQ, AQ, PLANNING, PRODUCTION';
COMMENT ON COLUMN "batch"."label" IS 'Étiquette de traçabilité';

ALTER TABLE "user_role" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "user_role" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "login_attempt" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "audit_trail" ADD FOREIGN KEY ("author_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "component" ADD FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "control_range_specifications" ADD FOREIGN KEY ("component_id") REFERENCES "component" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "order_line" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "order_line" ADD FOREIGN KEY ("component_id") REFERENCES "component" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "batch" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "batch" ADD FOREIGN KEY ("component_id") REFERENCES "component" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deviation" ADD FOREIGN KEY ("batch_id") REFERENCES "batch" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "analysis_results" ADD FOREIGN KEY ("batch_id") REFERENCES "batch" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "analysis_results" ADD FOREIGN KEY ("specification_id") REFERENCES "control_range_specifications" ("id") DEFERRABLE INITIALLY IMMEDIATE;
