CREATE TYPE user_role AS ENUM ('ADMIN', 'SUPPLY', 'AQ', 'CQ', 'PLANNING', 'PRODUCTION');

CREATE TABLE IF NOT EXISTS "users" (
    "id" UUID PRIMARY KEY,
    "login" VARCHAR(255) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "firstname" VARCHAR(255) NOT NULL,
    "surname" VARCHAR(255) NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('ACTIVE', 'LOCKED', 'ARCHIVED')),
    "roles" user_role[] NOT NULL,
    "version" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "login_attempts" (
    "user_id" UUID PRIMARY KEY,
    "count" INTEGER NOT NULL DEFAULT 0,
    "last_attempt" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "audit_trail" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "author_id" UUID,
    "event" VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMPTZ NOT NULL,
    "previous_data" JSONB NOT NULL,
    "changed_data" JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS "suppliers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "address" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "components" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" VARCHAR(15) NOT NULL CHECK (type IN ('RAW_MATERIAL', 'COMPONENT')),
    "reference" VARCHAR(255) UNIQUE NOT NULL,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('DRAFT', 'DISABLED', 'ACTIVE')),
    "supplier_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "control_range_specifications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "component_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "method" VARCHAR(255) NOT NULL,
    "unit" VARCHAR(255) NOT NULL,
    "min" DOUBLE PRECISION NOT NULL,
    "max" DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS "orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('PENDING', 'RECEIVED', 'CANCELED')),
    "version" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "orders_lines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "component_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "batches" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "component_id" BIGINT NOT NULL,
    "label" VARCHAR(255),
    "internal_reference_number" VARCHAR(255) UNIQUE NOT NULL,
    "supplier_reference_number" VARCHAR(255) UNIQUE NOT NULL,
    "expiry_date" DATE NOT NULL,
    "reception_date" DATE NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('QUARANTINE', 'PENDING', 'RECEIVED', 'USED', 'REFUSED', 'EXPIRED', 'DESTROYED')),
    "version" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "deviations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "batch_id" BIGINT NOT NULL,
    "code" VARCHAR(255) NOT NULL,
    "status" VARCHAR(15) NOT NULL CHECK (status IN ('OPENED', 'CLOSED')),
    "comment" TEXT
);

CREATE TABLE IF NOT EXISTS "analysis_results" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "batch_id" BIGINT NOT NULL,
    "specification_id" BIGINT NOT NULL,
    "value" DOUBLE PRECISION NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

COMMENT ON COLUMN "users"."version" IS 'Optimistic Locking';
COMMENT ON COLUMN "users"."roles" IS 'ADMIN, SUPPLY, CQ, AQ, PLANNING, PRODUCTION';
COMMENT ON COLUMN "batches"."label" IS 'Étiquette de traçabilité';

ALTER TABLE "login_attempts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "audit_trail" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "components" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "control_range_specifications" ADD FOREIGN KEY ("component_id") REFERENCES "components" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "orders_lines" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "orders_lines" ADD FOREIGN KEY ("component_id") REFERENCES "components" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "batches" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "batches" ADD FOREIGN KEY ("component_id") REFERENCES "components" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deviations" ADD FOREIGN KEY ("batch_id") REFERENCES "batches" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "analysis_results" ADD FOREIGN KEY ("batch_id") REFERENCES "batches" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "analysis_results" ADD FOREIGN KEY ("specification_id") REFERENCES "control_range_specifications" ("id") DEFERRABLE INITIALLY IMMEDIATE;
