spring:
  application:
    name: QualiTrace

  # Datasource configuration
  datasource:
      url: jdbc:postgresql://localhost:5432/qualitrace
      username: root
      password: P@ssw0rd
      driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
      hibernate:
          ddl-auto: validate
      show-sql: true # Pour voir les requêtes SQL dans la console (comme la barre de debug !)
      properties:
          hibernate:
              format_sql: true
      open-in-view: false

  # Configuration Redis
  data:
      redis:
          host: localhost
          port: 6379
  web:
    error:
      include-stacktrace: never

  session:
    store-type: redis
    timeout: 30m  # durée de vie d'une session inactive

# Configuration Actuator pour le debug
management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, env, beans, mappings, threaddump, heapdump
    endpoint:
        health:
            show-details: when_authorized
        env:
            show-values: when_authorized
    info:
        env:
            enabled: true
        java:
            enabled: true
        os:
            enabled: true

info:
    app:
        name: Qualitrace API
        description: API de gestion et traçabilité pharmaceutique (GxP)
        version: '${version}'

sentry:
    dsn: '${SENTRY_DSN:}'
    send-default-pii: true
    traces-sample-rate: 1.0 # 100% des erreurs et traces capturées en dev
    logging:
        minimum-event-level: error # Capture automatiquement les logs ERROR